/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/_search'
import { Route as SearchIndexRouteImport } from './routes/_search.index'
import { Route as RepositoryOwnerNameRouteImport } from './routes/repository.$owner.$name'
import { Route as RepositoryOwnerNameNumberRouteImport } from './routes/repository.$owner.$name.$number'
import { Route as RepositoryOwnerNameNumberIndexRouteImport } from './routes/repository.$owner.$name.$number.index'

const SearchRoute = SearchRouteImport.update({
  id: '/_search',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SearchRoute,
} as any)
const RepositoryOwnerNameRoute = RepositoryOwnerNameRouteImport.update({
  id: '/repository/$owner/$name',
  path: '/repository/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryOwnerNameNumberRoute =
  RepositoryOwnerNameNumberRouteImport.update({
    id: '/$number',
    path: '/$number',
    getParentRoute: () => RepositoryOwnerNameRoute,
  } as any)
const RepositoryOwnerNameNumberIndexRoute =
  RepositoryOwnerNameNumberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RepositoryOwnerNameNumberRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SearchIndexRoute
  '/repository/$owner/$name': typeof RepositoryOwnerNameRouteWithChildren
  '/repository/$owner/$name/$number': typeof RepositoryOwnerNameNumberRouteWithChildren
  '/repository/$owner/$name/$number/': typeof RepositoryOwnerNameNumberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SearchIndexRoute
  '/repository/$owner/$name': typeof RepositoryOwnerNameRouteWithChildren
  '/repository/$owner/$name/$number': typeof RepositoryOwnerNameNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_search': typeof SearchRouteWithChildren
  '/_search/': typeof SearchIndexRoute
  '/repository/$owner/$name': typeof RepositoryOwnerNameRouteWithChildren
  '/repository/$owner/$name/$number': typeof RepositoryOwnerNameNumberRouteWithChildren
  '/repository/$owner/$name/$number/': typeof RepositoryOwnerNameNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/repository/$owner/$name'
    | '/repository/$owner/$name/$number'
    | '/repository/$owner/$name/$number/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/repository/$owner/$name' | '/repository/$owner/$name/$number'
  id:
    | '__root__'
    | '/_search'
    | '/_search/'
    | '/repository/$owner/$name'
    | '/repository/$owner/$name/$number'
    | '/repository/$owner/$name/$number/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SearchRoute: typeof SearchRouteWithChildren
  RepositoryOwnerNameRoute: typeof RepositoryOwnerNameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_search': {
      id: '/_search'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_search/': {
      id: '/_search/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof SearchRoute
    }
    '/repository/$owner/$name': {
      id: '/repository/$owner/$name'
      path: '/repository/$owner/$name'
      fullPath: '/repository/$owner/$name'
      preLoaderRoute: typeof RepositoryOwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository/$owner/$name/$number': {
      id: '/repository/$owner/$name/$number'
      path: '/$number'
      fullPath: '/repository/$owner/$name/$number'
      preLoaderRoute: typeof RepositoryOwnerNameNumberRouteImport
      parentRoute: typeof RepositoryOwnerNameRoute
    }
    '/repository/$owner/$name/$number/': {
      id: '/repository/$owner/$name/$number/'
      path: '/'
      fullPath: '/repository/$owner/$name/$number/'
      preLoaderRoute: typeof RepositoryOwnerNameNumberIndexRouteImport
      parentRoute: typeof RepositoryOwnerNameNumberRoute
    }
  }
}

interface SearchRouteChildren {
  SearchIndexRoute: typeof SearchIndexRoute
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchIndexRoute: SearchIndexRoute,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

interface RepositoryOwnerNameNumberRouteChildren {
  RepositoryOwnerNameNumberIndexRoute: typeof RepositoryOwnerNameNumberIndexRoute
}

const RepositoryOwnerNameNumberRouteChildren: RepositoryOwnerNameNumberRouteChildren =
  {
    RepositoryOwnerNameNumberIndexRoute: RepositoryOwnerNameNumberIndexRoute,
  }

const RepositoryOwnerNameNumberRouteWithChildren =
  RepositoryOwnerNameNumberRoute._addFileChildren(
    RepositoryOwnerNameNumberRouteChildren,
  )

interface RepositoryOwnerNameRouteChildren {
  RepositoryOwnerNameNumberRoute: typeof RepositoryOwnerNameNumberRouteWithChildren
}

const RepositoryOwnerNameRouteChildren: RepositoryOwnerNameRouteChildren = {
  RepositoryOwnerNameNumberRoute: RepositoryOwnerNameNumberRouteWithChildren,
}

const RepositoryOwnerNameRouteWithChildren =
  RepositoryOwnerNameRoute._addFileChildren(RepositoryOwnerNameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SearchRoute: SearchRouteWithChildren,
  RepositoryOwnerNameRoute: RepositoryOwnerNameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
